### ISSUE TITLE
Phaser3 - SpritesAndGraphics.js

### ISSUE THREAD

**Issue by EneaEntertainment** [themoonrat/webgl-benchmark#1]
https://github.com/themoonrat/webgl-benchmark/blob/master/src/js/phaser3/scenes/SpritesAndGraphics.js#L29-L31

should be

const graphic = this._app.scene.add.graphics({ fillStyle: { color } });
graphic.fillRectShape(new Phaser.Geom.Rectangle(-15, -15, 30, 30));

**Comment by themoonrat** [comment]
Cheers for the report! Now fixed :)
